name: Checks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy -D warnings

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo MONOBANK_TOKEN=${{ secrets.MONOBANK_TOKEN }} >> .env && cargo test --verbose
